//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService_Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTakeVarianceLineItem
    {
        public int StockTakeVarianceLineItemID { get; set; }
        public int StockTakeID { get; set; }
        public Nullable<int> CastingID { get; set; }
        public Nullable<int> SampleID { get; set; }
        public Nullable<int> DieID { get; set; }
        public Nullable<int> AlloyID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public bool WithRunners { get; set; }
        public bool IsCasting { get; set; }
    
        public virtual Alloy Alloy { get; set; }
        public virtual Casting Casting { get; set; }
        public virtual Die Die { get; set; }
        public virtual Sample Sample { get; set; }
        public virtual StockTake StockTake { get; set; }
    }
}
